"""
预设审计程序模板
包含穿行测试、控制测试等标准化模板
"""

from app.models.audit_procedure import ProcedureType, ItemDataType

PRESET_PROCEDURES = [
    {
        "procedure_code": "WT-SALES-001",
        "name": "门窗销售系统穿行测试",
        "procedure_type": ProcedureType.WALKTHROUGH,
        "target_process": "门窗销售系统",
        "description": "对门窗销售全流程进行穿行测试，覆盖订单创建→审批→生产→发货→开票→收款全环节",
        "data_sources": ["erp", "srm", "yunzhijia", "crm"],
        "version": "1.0",
        "is_preset": True,
        "items": [
            {"sort_order": 1, "field_name": "customer_name", "field_label": "客户名称",
             "data_type": ItemDataType.TEXT, "data_source": "ERP", "is_required": True},
            {"sort_order": 2, "field_name": "has_sales_order", "field_label": "是否存在销售订单",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["是", "否"], "expected_result": "是"},
            {"sort_order": 3, "field_name": "manual_closure", "field_label": "手工关闭情况",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["正常", "手工关闭", "系统关闭"],
             "placeholder": "如为手工关闭需说明原因"},
            {"sort_order": 4, "field_name": "closure_reason", "field_label": "手工关闭情况说明",
             "data_type": ItemDataType.TEXT, "is_required": False,
             "placeholder": "如为空说明原因"},
            {"sort_order": 5, "field_name": "has_rebate_contract", "field_label": "是否有返利合同",
             "data_type": ItemDataType.SELECT, "data_source": "CRM/SRM",
             "options": ["是", "否", "不适用"],
             "expected_result": "若有返利需有合同"},
            {"sort_order": 6, "field_name": "rebate_details", "field_label": "返利情况",
             "data_type": ItemDataType.TEXT, "data_source": "CRM",
             "is_required": False, "placeholder": "返利比例/金额"},
            {"sort_order": 7, "field_name": "contract_status", "field_label": "合同情况",
             "data_type": ItemDataType.SELECT, "data_source": "SRM/CRM",
             "options": ["正常", "已过期", "无合同", "即将到期"],
             "expected_result": "正常"},
            {"sort_order": 8, "field_name": "contract_remark", "field_label": "具体情况说明",
             "data_type": ItemDataType.TEXT, "is_required": False,
             "placeholder": "合同编号、有效期等"},
            {"sort_order": 9, "field_name": "slow_moving", "field_label": "呆滞情况",
             "data_type": ItemDataType.SELECT, "data_source": "WMS/ERP",
             "options": ["正常流转", "呆滞超30天", "呆滞超60天", "呆滞超90天"],
             "expected_result": "正常流转"},
            {"sort_order": 10, "field_name": "sales_amount", "field_label": "订单金额（元）",
             "data_type": ItemDataType.NUMBER, "data_source": "ERP",
             "is_required": True},
            {"sort_order": 11, "field_name": "payment_terms", "field_label": "付款条件",
             "data_type": ItemDataType.TEXT, "data_source": "ERP/合同",
             "placeholder": "如：月结30天、预付30%"},
            {"sort_order": 12, "field_name": "delivery_status", "field_label": "发货情况",
             "data_type": ItemDataType.SELECT, "data_source": "WMS/ERP",
             "options": ["已发货", "部分发货", "未发货", "不适用"]},
            {"sort_order": 13, "field_name": "invoice_status", "field_label": "开票情况",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["已开票", "未开票", "部分开票", "不适用"]},
            {"sort_order": 14, "field_name": "approval_chain", "field_label": "审批流程完整性",
             "data_type": ItemDataType.SELECT, "data_source": "云之家OA",
             "options": ["完整", "缺审批", "已跳过", "无法确认"],
             "expected_result": "完整"},
            {"sort_order": 15, "field_name": "conclusion", "field_label": "测试结论",
             "data_type": ItemDataType.SELECT,
             "options": ["正常", "异常", "待确认"],
             "is_required": True},
        ]
    },
    {
        "procedure_code": "WT-PURCHASE-001",
        "name": "采购付款系统穿行测试",
        "procedure_type": ProcedureType.WALKTHROUGH,
        "target_process": "采购付款系统",
        "description": "对采购付款全流程进行穿行测试，覆盖请购→询价→下单→入库→对账→付款全环节",
        "data_sources": ["erp", "srm", "yunzhijia"],
        "version": "1.0",
        "is_preset": True,
        "items": [
            {"sort_order": 1, "field_name": "supplier_name", "field_label": "供应商名称",
             "data_type": ItemDataType.TEXT, "data_source": "SRM/ERP", "is_required": True},
            {"sort_order": 2, "field_name": "purchase_type", "field_label": "采购类型",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["原材料", "备品备件", "办公用品", "服务采购", "固定资产"]},
            {"sort_order": 3, "field_name": "has_pr", "field_label": "是否有请购单",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["是", "否"], "expected_result": "是"},
            {"sort_order": 4, "field_name": "has_po", "field_label": "是否有采购订单",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["是", "否"], "expected_result": "是"},
            {"sort_order": 5, "field_name": "has_contract", "field_label": "是否有采购合同",
             "data_type": ItemDataType.SELECT, "data_source": "SRM",
             "options": ["是", "否"], "expected_result": "是"},
            {"sort_order": 6, "field_name": "quotation_count", "field_label": "询价比价次数",
             "data_type": ItemDataType.NUMBER, "data_source": "SRM",
             "expected_result": ">=3", "placeholder": "应至少3家询价"},
            {"sort_order": 7, "field_name": "gr_status", "field_label": "收货情况",
             "data_type": ItemDataType.SELECT, "data_source": "WMS/ERP",
             "options": ["已收货", "部分收货", "未收货", "不适用"]},
            {"sort_order": 8, "field_name": "invoice_match", "field_label": "票单一致性",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["一致", "不一致", "待确认"],
             "expected_result": "一致",
             "remark": "发票金额与采购订单金额是否一致"},
            {"sort_order": 9, "field_name": "payment_review", "field_label": "付款审批完整性",
             "data_type": ItemDataType.SELECT, "data_source": "云之家OA",
             "options": ["完整", "缺审批", "已跳过", "无法确认"],
             "expected_result": "完整"},
            {"sort_order": 10, "field_name": "conclusion", "field_label": "测试结论",
             "data_type": ItemDataType.SELECT,
             "options": ["正常", "异常", "待确认"],
             "is_required": True},
        ]
    },
    {
        "procedure_code": "CT-EXPENSE-001",
        "name": "费用报销控制测试",
        "procedure_type": ProcedureType.CONTROL_TEST,
        "target_process": "费用报销流程",
        "description": "测试费用报销流程的关键控制点有效性",
        "data_sources": ["erp", "yunzhijia"],
        "version": "1.0",
        "is_preset": True,
        "items": [
            {"sort_order": 1, "field_name": "expense_no", "field_label": "报销单号",
             "data_type": ItemDataType.TEXT, "data_source": "云之家OA"},
            {"sort_order": 2, "field_name": "expense_type", "field_label": "费用类型",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["差旅费", "招待费", "办公费", "通讯费", "培训费", "其他"]},
            {"sort_order": 3, "field_name": "amount", "field_label": "报销金额（元）",
             "data_type": ItemDataType.NUMBER, "data_source": "ERP"},
            {"sort_order": 4, "field_name": "has_receipt", "field_label": "是否有发票/收据",
             "data_type": ItemDataType.SELECT, "data_source": "人工审核",
             "options": ["是", "否", "部分有"], "expected_result": "是"},
            {"sort_order": 5, "field_name": "approval_complete", "field_label": "审批流是否完整",
             "data_type": ItemDataType.SELECT, "data_source": "云之家OA",
             "options": ["完整", "缺审批", "已跳过"], "expected_result": "完整"},
            {"sort_order": 6, "field_name": "budget_check", "field_label": "是否在预算内",
             "data_type": ItemDataType.SELECT, "data_source": "ERP",
             "options": ["预算内", "超预算", "无预算"], "expected_result": "预算内"},
            {"sort_order": 7, "field_name": "conclusion", "field_label": "测试结论",
             "data_type": ItemDataType.SELECT,
             "options": ["正常", "异常", "待确认"],
             "is_required": True},
        ]
    },
]
